### DISCUSSION TITLE
Clash Pre-Process Settings is There even after deleting Origin Server Config File

### DISCUSSION THREAD

**Discussion by String10** [String10/KGarden#25] [Issues]
yesterday i found that the proxy provider changed their domain for the proxy download server, so i quickly set the newer one and delete the other one. however, today i just realized that maybe i delete the pre-process settings for the server config. 😭

then the most surprising thing happened: i tried to add another pre-process setting from scratch and found that the settings was amazingly there with a deprecated url, so i just update the url and then everything goes fine.

pre-process setting yaml format:
``` YAML
parsers:
  - url: xxx
    yaml:
      append-proxies:
        - name: xxx-proxy
          type: http
          server: xxx
          port: xxx
      append-proxy-groups:
        - name: xxx-group
          type: select
          proxies:
            - xxx-proxy
            - DIRECT
      prepend-rules:
        - DOMAIN-SUFFIX,xxx.net,DIRECT
        - DOMAIN,xxx.cn,DIRECT
```
